model_params:
  model_type: logistic_regression
  C: 1
  penalty: l1
  solver: liblinear
  random_state: 777

feature_params:
  num_cols: ['age', 'fnlwgt', 'educational-num', 'capital-gain', 'capital-loss', 'hours-per-week']
  cat_cols: ['workclass', 'education', 'marital-status', 'occupation', 'relationship', 'race', 'gender', 'native-country']
  target_col: 'income'

split_params:
  test_size: 0.2
  random_state: 777
