model_params:
  bootstrap: true
  ccp_alpha: 0.0
  class_weight: null
  criterion: gini
  max_depth: 12
  max_features: sqrt
  max_leaf_nodes: null
  max_samples: null
  min_impurity_decrease: 0.0
  min_samples_leaf: 1
  min_samples_split: 2
  min_weight_fraction_leaf: 0.0
  monotonic_cst: null
  n_estimators: 150
  n_jobs: null
  oob_score: false
  random_state: 777
  verbose: 0
  warm_start: false
feature_params:
  num_cols:
  - age
  - fnlwgt
  - education.num
  - capital.gain
  - capital.loss
  - hours.per.week
  cat_cols:
  - workclass
  - education
  - marital.status
  - occupation
  - relationship
  - race
  - sex
  - native.country
  target_col: income
split_params:
  test_size: 0.2
  random_state: 777
model_configs:
  model_type: RandomForestClassifier
  threshold: 0.3902859252443551
